import { describe, expect, it } from 'vitest'

import { SQLITE_CAPABILITIES } from '../../../src/main/storage/sqlite/SqliteStorageSession'
import { POSTGRES_CAPABILITIES } from '../../../src/main/storage/postgres/PostgresStorageSession'

describe('backend capabilities', () => {
  it('declares SQLite as the complete local backend', () => {
    expect(SQLITE_CAPABILITIES.backend).toBe('sqlite')
    expect(SQLITE_CAPABILITIES.workspace.localFileLifecycle).toBe(true)
    expect(SQLITE_CAPABILITIES.workspace.encryptionAtRest).toBe(true)
    expect(SQLITE_CAPABILITIES.variants.filterOptions).toBe(true)
    expect(SQLITE_CAPABILITIES.variants.columnMeta).toBe(true)
    expect(SQLITE_CAPABILITIES.export.variants).toBe(true)
  })

  it('declares current PostgreSQL support and known deferrals explicitly', () => {
    expect(POSTGRES_CAPABILITIES.backend).toBe('postgres')
    expect(POSTGRES_CAPABILITIES.workspace.hostedConnectionLifecycle).toBe(true)
    expect(POSTGRES_CAPABILITIES.workspace.migrations).toBe(true)
    expect(POSTGRES_CAPABILITIES.imports.vcf).toBe(true)
    expect(POSTGRES_CAPABILITIES.imports.multiFileVcf).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.query).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.searchQuery).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.legacySearch).toBe(false)
    expect(POSTGRES_CAPABILITIES.variants.filterOptions).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.columnMeta).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.panelFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.tagFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.commentFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.acmgFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.annotationFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.inheritanceFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.analysisGroupFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.variants.phasingFilters).toBe(true)
    expect(POSTGRES_CAPABILITIES.export.variants).toBe(true)
    expect(POSTGRES_CAPABILITIES.export.cohort).toBe(true)
    expect(POSTGRES_CAPABILITIES.export.streaming).toBe(true)
    expect(POSTGRES_CAPABILITIES.cohort.query).toBe(true)
    expect(POSTGRES_CAPABILITIES.cohort.summary).toBe(true)
    expect(POSTGRES_CAPABILITIES.cohort.rebuild).toBe(false)
    expect(POSTGRES_CAPABILITIES.cohort.carriers).toBe(true)
    expect(POSTGRES_CAPABILITIES.cohort.geneBurden).toBe(true)
    expect(POSTGRES_CAPABILITIES.cohort.columnMeta).toBe(true)
    expect(POSTGRES_CAPABILITIES.cases.deleteOne).toBe(true)
    expect(POSTGRES_CAPABILITIES.cases.deleteMany).toBe(false)
    expect(POSTGRES_CAPABILITIES.cases.deleteAll).toBe(false)
    expect(POSTGRES_CAPABILITIES.cases.overview).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.tags).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.annotations).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.caseComments).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.caseMetrics).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.filterPresets).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.panels).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.geneLists).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.regionFiles).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.analysisGroups).toBe(true)
    expect(POSTGRES_CAPABILITIES.workflow.auditLog).toBe(false)
  })
})
